<?php

/**
 * @file
 * Simple form placed in block.
 */

/**
 * Implements hook_block_info().
 */
function phantomjs_capture_block_block_info() {
  $blocks['screenshot'] = array(
    'info' => t('Screenshot'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function phantomjs_capture_block_block_view($delta = '') {
  $block = array();
  if ($delta === 'screenshot') {
    $block['title'] = t('Screenshot');
    $block['content'] = drupal_get_form('phantomjs_capture_block_form');
  }
  return $block;
}

/**
 * Simple form.
 */
function phantomjs_capture_block_form($form, &$form_state) {
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL'),
    '#ajax' => array(
      'callback' => 'phantomjs_capture_block_form_callback',
      'wrapper' => 'phantomjs-capture-block-form-preview',
      'method' => 'replace',
    ),
  );

  $form['preview'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'id' => 'phantomjs-capture-block-form-preview',
    ),
  );

  if (!empty($form_state['values']['url'])) {
    $directory = 'public://';
    $filename = REQUEST_TIME . '.png';
    if (phantomjs_capture_screen($form_state['values']['url'], $directory, $filename)) {
      $form['preview']['image'] = array(
        '#theme' => 'image',
        '#path' => $directory . '/' . $filename,
        '#width' => '100%',
      );
    }
    else {
      drupal_set_message(t('Unable to create screenshot'), 'error');
    }
  }

  return $form;
}

function phantomjs_capture_block_form_callback($form, $form_state) {
 return $form['preview'];
}
